# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20150703_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='college',
            field=models.CharField(choices=[('', 'الكلية'), ('M', 'كلية الطب'), ('D', 'كلية الأسنان'), ('P', 'كلية الصيدلة'), ('N', 'كلية التمريض'), ('FMRTP', 'Family Medicine Residency Training Program')], max_length=10, verbose_name='الكلية'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='unisersity_id',
            field=models.PositiveIntegerField(null=True, verbose_name='الرقم الجامعي'),
        ),
    ]
